server:
  servlet:
    context-path: /frontservice

spring:
  application:
    name: frontservice
  jmx:
    enabled: false

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,shutdown
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,requestPool
        liveness:
          include: livenessState,diskSpace,fragileComponent
      show-details: always
    shutdown:
      enabled: true